### ISSUE TITLE
Robot Educator model

### ISSUE THREAD

**Issue by dwalton76** [ev3dev/ev3dev-lang-python-demo#2]
We need a demo for this one...see ndward's comment in https://github.com/rhempel/ev3dev-lang-python/issues/338

**Comment by gregcowell** [comment]
I'd like to write this demo script if that's okay. If yes, could I please confirm that I should use the future 'high level' API.

**Comment by WasabiFan** [comment]
@gregcowell that sounds great! I'd say that the high-level APIs (the ones that are modelled after the EV3-G blocks) are what we should base all our demos on, but we should hear from others on that (I know there were some differing opinions).

It's worth noting that, so far, we haven't updated the demos here for the breaking changes we're working on for the upcoming Stretch release. None of the demos will work until we update the imports, at a minimum. Demos we implement from here forward will need to use the new import model and other APIs, which is only partially documented right now.

**Comment by dwalton76** [comment]
+1 on using the high-level APIs

**Comment by gregcowell** [comment]
Sounds good. I prefer the high level API.  

I am planning to do five simple example scripts:
* square.py (moving forward and turning)
* touch.py (moving forward until touching wall then reversing back again)
* ultrasonic.py (using ultrasonic sensor and medium motor to re-position a cuboid)
* gyro.py (turning using gyro sensor)
* color.py (naming the observed color)

For something more challenging, I could write a simple maze solving script. I've got this already working as an EV3-G program and I can translate it to Python.

**Comment by dwalton76** [comment]
Resolved by gregcowell
