### ISSUE TITLE
Attribute `connected` is no longer available for motors

### ISSUE THREAD

**Issue by loopspace** [ev3dev/ev3dev-lang-python-demo#41]
I noticed this in the code for the MINDCUB3R, specifically in `mindcuber.py` lines 71-73 there is reference to the `connected` attribute of the various motors.

Section 6.1.2 of [the documentation](https://media.readthedocs.org/pdf/python-ev3dev/ev3dev-stretch/python-ev3dev.pdf) says that this attribute no longer exists.  Commenting out these lines certainly makes it work (though perhaps the check for connection should still happen somewhere, perhaps by testing for the exception when the motors are initialised).

A quick grep of the code suggests that this also affects EV3D4, EV3RSTORM, and TRACK3R.

**Comment by dwalton76** [comment]
all fixed
