### ISSUE TITLE
ev3dev2.sound.Sound.play_song converts notes to uppercase and breaks flats

### ISSUE THREAD

**Issue by lisjump** [ev3dev/ev3dev-lang-python-demo#44]
Sound.play_song((
  ('Db4', 'e3')
))

will produce an error "Invalid Note: DB4"  
Sharps work, so I think this is because the b has been capitalized in self._NOTE_FREQUENCIES[note.upper()] and is different than the key error that happens when you have an actual invalid note.

**Comment by WasabiFan** [comment]
It looks like this is about the main ev3dev-lang-python library, not the demo repo. Please reopen this issue at https://github.com/ev3dev/ev3dev-lang-python/issues.

**Comment by lisjump** [comment]
Oops!  I thought the open list looked pretty small!  Sorry!
