### ISSUE TITLE
Problem with MINDCUB3R code

### ISSUE THREAD

**Issue by guinasc2** [ev3dev/ev3dev-lang-python-demo#47]
I followed all the steps on how to install the code for MINDCUB3R. When I try to execute the code, I get an exception saying that the Infrared Sensor is not connected even though it is connected. Is there anything I can do to solve this problem?

**Comment by WasabiFan** [comment]
Does the device appear in the Device Browser (accessible via the on-screen menu of the brick)?

**Comment by guinasc2** [comment]
Yes. I can even see the values the device is reading.

**Comment by WasabiFan** [comment]
Hmmmm... Are you able to run other Python code that uses the IR sensor? (And to clarify, you're definitely running the code on your EV3?)

Try this: run the command `python3` then type:

```
from ev3dev2.sensor.lego import InfraredSensor
sensor = InfraredSensor()
```

Does it print an error?

**Comment by guinasc2** [comment]
I will only be able to test this code on Thursday. Is there a problem if I answer you later?

**Comment by WasabiFan** [comment]
No problem; let us know when you can.

**Comment by guinasc2** [comment]
Hi. I tested the code you passed on EV3 and returned this error:

>>> from ev3dev2.sensor.lego import InfraredSensor
>>> sensor = InfraredSensor()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/lego.py", line 744, in __init__
    super(InfraredSensor, self).__init__(address, name_pattern, name_exact, driver_name='lego-ev3-ir', **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 91, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 201, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 38, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: InfraredSensor is not connected.

What should I do?

**Comment by WasabiFan** [comment]
Interesting. The Python library certainly isn't seeing the sensor. Do you have a terminal connection to your brick available (e.g. via vscode or SSH)? Can you connect the sensor then run the following commands and give me the output? They will list the port info and detected sensor type for all connected sensors.

```
tail -n +1 /sys/class/lego-sensor/sensor*/address
```

and

```
tail -n +1 /sys/class/lego-sensor/sensor*/driver_name
```

**Comment by guinasc2** [comment]
These are the outputs of the commands:

robot@ev3dev:~$ tail -n +1 /sys/class/lego-sensor/sensor*/address

==> /sys/class/lego-sensor/sensor0/address <==
ev3-ports:in1

==> /sys/class/lego-sensor/sensor1/address <==
ev3-ports:in2




robot@ev3dev:~$ tail -n +1 /sys/class/lego-sensor/sensor*/driver_name

==> /sys/class/lego-sensor/sensor0/driver_name <==
lego-ev3-us

==> /sys/class/lego-sensor/sensor1/driver_name <==
lego-ev3-color

**Comment by ddemidov** [comment]
Looks like this is an `UltrasonicSensor`, and not an infrared one.

**Comment by guinasc2** [comment]
That makes sense, but in the building instruction using the Education Sets available at http://mindcuber.com/, the sensor they show is an ultrasonic sensor, so I used it.
I would like to know if it is possible to change the code to make it work with the ultrasonic sensor because I do not have the infrared sensor.

**Comment by WasabiFan** [comment]
You can probably replace `InfraredSensor` with `UltrasonicSensor` here (https://github.com/ev3dev/ev3dev-lang-python-demo/blob/stretch/robots/MINDCUB3R/mindcuber.py#L44) then replace `proximity` with `distance_cm` here (https://github.com/ev3dev/ev3dev-lang-python-demo/blob/stretch/robots/MINDCUB3R/mindcuber.py#L478) and change the threshold in the "if" a few lines below from 50 to a smaller number, maybe 5.

**Comment by guinasc2** [comment]
I made the changes you suggested and it worked! Many thanks for your help and apologies for the inconvenience.

**Comment by WasabiFan** [comment]
Glad to hear it, no problem!
